# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50d5d4e5ee2f1c0a95525421882e43890d4e6252e14a6e691e4df91c12e0c215f4d8e2fa73be7fdd2f118c592a4d3f486a734a2dba5f9860b5f67394db24b36c

test:
  secret_key_base: 6ff79634c5f3fdb8a14dfaf8efc3a898a49488e9308a410a88d4227f29cb1a7cba8df8d403a59e56daddf47f273b30cd5a4badc8388e3741d3843a82eb67739a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
